# Generated by Django 3.2.1 on 2023-03-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.PositiveIntegerField(help_text='Enter name', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter name', max_length=200)),
                ('apellido', models.CharField(help_text='Enter surname', max_length=200)),
                ('email', models.EmailField(help_text='Enter email', max_length=254)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
